[package]
name = "ytar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ytar"
path = "src/lib.rs"

[[bin]]
name = "ytar"
path = "src/main.rs"

[dependencies]
zerocopy = "0.6"
walkdir = "2"
